# Generated by Django 5.0.6 on 2024-06-10 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiAnnual2024Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('line_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SemiAnnual2024CreatorsSummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creators', models.ManyToManyField(related_name='summary_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemiAnnual2024Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_1', models.PositiveIntegerField(default=0, verbose_name='Штатная численность СБ (чел.)')),
                ('field_2', models.PositiveIntegerField(default=0, verbose_name='Фактическая численность СБ (чел.) на 31.05.2024')),
                ('field_3', models.PositiveIntegerField(default=0, verbose_name='Направлено заявлений в правоохранительные органы за период с 01.01 по 31.05.2024 (кол-во без дебиторской задолженности)')),
                ('field_4', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Заявленный причиненный ущерб по заявлениям из предыдущего столбца (млн руб.)')),
                ('field_5', models.PositiveIntegerField(default=0, verbose_name='158')),
                ('field_6', models.PositiveIntegerField(default=0, verbose_name='159')),
                ('field_7', models.PositiveIntegerField(default=0, verbose_name='165')),
                ('field_8', models.PositiveIntegerField(default=0, verbose_name='160')),
                ('field_9', models.PositiveIntegerField(default=0, verbose_name='204')),
                ('field_10', models.PositiveIntegerField(default=0, verbose_name='247')),
                ('field_11', models.PositiveIntegerField(default=0, verbose_name='др.')),
                ('field_12', models.PositiveIntegerField(default=0, verbose_name='Кол-во оконченых расследованием уд с направлением в суд за период с 01.01 по 31.05.2024 из сопровождаемых (с остатком прошлых лет)')),
                ('field_13', models.PositiveIntegerField(default=0, verbose_name='Кол-во приговоров вступивших в законную силу за период с 01.01 по 31.05.2024 по сопровождаемым уголовным делам (с остатком прошлых лет)')),
                ('field_14', models.PositiveIntegerField(default=0, verbose_name='Ходатайств')),
                ('field_15', models.PositiveIntegerField(default=0, verbose_name='Жалоб')),
                ('field_16', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Уголовного преследования')),
                ('field_17', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Доследственных проверок')),
                ('field_18', models.PositiveIntegerField(default=0, verbose_name='Уголовных дел')),
                ('field_19', models.PositiveIntegerField(default=0, verbose_name='Материалов проверок')),
                ('field_20', models.PositiveIntegerField(default=0, verbose_name='Выявлено фактов с 01.01. по 31.05.2024')),
                ('field_21', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='По данным фактам причинен ущерб (млн руб.)')),
                ('field_22', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='По данным фактам возмещен ущерб (млн руб.)')),
                ('field_23', models.PositiveIntegerField(default=0, verbose_name='Привлечено к ответственности')),
                ('field_24', models.PositiveIntegerField(default=0, verbose_name='В т.ч. руководителей')),
                ('field_25', models.PositiveIntegerField(default=0, verbose_name='Уволено')),
                ('field_26', models.PositiveIntegerField(default=0, verbose_name='Проведено проверок несения службы за период с 01.01. по 31.05.2024')),
                ('field_27', models.PositiveIntegerField(default=0, verbose_name='Пропускного и внутриобъектового режимов')),
                ('field_28', models.PositiveIntegerField(default=0, verbose_name='Исполнения работниками охранных предприятий своих обязанностей')),
                ('field_29', models.PositiveIntegerField(default=0, verbose_name='др.')),
                ('field_30', models.PositiveIntegerField(default=0, verbose_name='По выявленным нарушениям направлено претензионных писем за период с 01.01 по 31.05.2024')),
                ('field_31', models.PositiveIntegerField(default=0, verbose_name='Привлечено к дисциплинарной ответственности')),
                ('field_32', models.PositiveIntegerField(default=0, verbose_name='Уволено')),
                ('field_33', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Удержана неустойка на сумму (млн руб)')),
                ('field_34', models.PositiveIntegerField(default=0, verbose_name='В период с 01.01 по 31.05.2024 изучено юр. лиц (подрядчики , субподрядчики), принявшие участие в закупочных процедурах (кол-во)')),
                ('field_35', models.PositiveIntegerField(default=0, verbose_name='Из них обоснованно отклонены')),
                ('field_36', models.PositiveIntegerField(default=0, verbose_name='Изучено физ. лиц , заявившихся к трудоустройству, а также собственники или руководители потенциальных подрядчиков (кол-во)')),
                ('field_37', models.PositiveIntegerField(default=0, verbose_name='Из них обоснованно отклонены')),
                ('field_38', models.PositiveIntegerField(default=0, verbose_name='Работники компании')),
                ('field_39', models.PositiveIntegerField(default=0, verbose_name='Подрядчики')),
                ('field_40', models.PositiveIntegerField(default=0, verbose_name='Сторонние лица')),
                ('field_41', models.PositiveIntegerField(default=0, verbose_name='Работники компании')),
                ('field_42', models.PositiveIntegerField(default=0, verbose_name='Подрядчики')),
                ('field_43', models.PositiveIntegerField(default=0, verbose_name='Сторонние лица')),
                ('field_44', models.PositiveIntegerField(default=0, verbose_name='Кол-во')),
                ('field_45', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Ущерб (млн руб)')),
                ('field_46', models.PositiveIntegerField(default=0, verbose_name='Кол-во')),
                ('field_47', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Ущерб (млн руб)')),
                ('field_48', models.PositiveIntegerField(default=0, verbose_name='Тематические сообщения о деятельности СБ')),
                ('field_49', models.PositiveIntegerField(default=0, verbose_name='Справочные материалы в рамках установленной отчетности')),
                ('field_50', models.PositiveIntegerField(default=0, verbose_name='Служебные записки руководству по проблемным вопросам, требующим мер реагирования')),
                ('field_51', models.PositiveIntegerField(default=0, verbose_name='Инициативные информационные письма, направленные в ФОИВ и региональные , а также правоохранительные органы о проблемных вопросах, требующих рассмотрения (не ответы на запросы)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixmonths2024.semiannual2024company', verbose_name='Компания/Филиал ПАО "Т Плюс"')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='SemiAnnual2024UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies', models.ManyToManyField(to='sixmonths2024.semiannual2024company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
