# Generated by Django 5.0.6 on 2024-06-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmonths2024', '0002_usercompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='field_1',
            field=models.PositiveIntegerField(default=0, verbose_name='Штатная численность СБ (чел.)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_10',
            field=models.PositiveIntegerField(default=0, verbose_name='247'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_11',
            field=models.PositiveIntegerField(default=0, verbose_name='др.'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во оконченых расследованием уд с направлением в суд за период с 01.01 по 31.05.2024 из сопровождаемых (с остатком прошлых лет)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_13',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во приговоров вступивших в законную силу за период с 01.01 по 31.05.2024 по сопровождаемым уголовным делам (с остатком прошлых лет)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_14',
            field=models.PositiveIntegerField(default=0, verbose_name='Ходатайств'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_15',
            field=models.PositiveIntegerField(default=0, verbose_name='Жалоб'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_16',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Уголовного преследования'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_17',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Доследственных проверок'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_18',
            field=models.PositiveIntegerField(default=0, verbose_name='Уголовных дел'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_19',
            field=models.PositiveIntegerField(default=0, verbose_name='Материалов проверок'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Фактическая численность СБ (чел.) на 31.05.2024'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_20',
            field=models.PositiveIntegerField(default=0, verbose_name='Выявлено фактов с 01.01. по 31.05.2024'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_21',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='По данным фактам причинен ущерб (млн руб.)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_22',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='По данным фактам возмещен ущерб (млн руб.)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_23',
            field=models.PositiveIntegerField(default=0, verbose_name='Привлечено к ответственности'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_24',
            field=models.PositiveIntegerField(default=0, verbose_name='В т.ч. руководителей'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_25',
            field=models.PositiveIntegerField(default=0, verbose_name='Уволено'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_26',
            field=models.PositiveIntegerField(default=0, verbose_name='Проведено проверок несения службы за период с 01.01. по 31.05.2024'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_27',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропускного и внутриобъектового режимов'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_28',
            field=models.PositiveIntegerField(default=0, verbose_name='Исполнения работниками охранных предприятий своих обязанностей'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_29',
            field=models.PositiveIntegerField(default=0, verbose_name='др.'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_3',
            field=models.PositiveIntegerField(default=0, verbose_name='Направлено заявлений в правоохранительные органы за период с 01.01 по 31.05.2024 (кол-во без дебиторской задолженности)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_30',
            field=models.PositiveIntegerField(default=0, verbose_name='По выявленным нарушениям направлено претензионных писем за период с 01.01 по 31.05.2024'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_31',
            field=models.PositiveIntegerField(default=0, verbose_name='Привлечено к дисциплинарной ответственности'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_32',
            field=models.PositiveIntegerField(default=0, verbose_name='Уволено'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_33',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Удержана неустойка на сумму (млн руб)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_34',
            field=models.PositiveIntegerField(default=0, verbose_name='В период с 01.01 по 31.05.2024 изучено юр. лиц (подрядчики , субподрядчики), принявшие участие в закупочных процедурах (кол-во)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_35',
            field=models.PositiveIntegerField(default=0, verbose_name='Из них обоснованно отклонены'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_36',
            field=models.PositiveIntegerField(default=0, verbose_name='Изучено физ. лиц , заявившихся к трудоустройству, а также собственники или руководители потенциальных подрядчиков (кол-во)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_37',
            field=models.PositiveIntegerField(default=0, verbose_name='Из них обоснованно отклонены'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_38',
            field=models.PositiveIntegerField(default=0, verbose_name='Работники компании'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_39',
            field=models.PositiveIntegerField(default=0, verbose_name='Подрядчики'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_4',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Заявленный причиненный ущерб по заявлениям из предыдущего столбца (млн руб.)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_40',
            field=models.PositiveIntegerField(default=0, verbose_name='Сторонние лица'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_41',
            field=models.PositiveIntegerField(default=0, verbose_name='Работники компании'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_42',
            field=models.PositiveIntegerField(default=0, verbose_name='Подрядчики'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_43',
            field=models.PositiveIntegerField(default=0, verbose_name='Сторонние лица'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_44',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_45',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Ущерб (млн руб)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_46',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_47',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Ущерб (млн руб)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_48',
            field=models.PositiveIntegerField(default=0, verbose_name='Тематические сообщения о деятельности СБ'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_49',
            field=models.PositiveIntegerField(default=0, verbose_name='Справочные материалы в рамках установленной отчетности'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_5',
            field=models.PositiveIntegerField(default=0, verbose_name='158'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_50',
            field=models.PositiveIntegerField(default=0, verbose_name='Служебные записки руководству по проблемным вопросам, требующим мер реагирования'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_51',
            field=models.PositiveIntegerField(default=0, verbose_name='Инициативные информационные письма, направленные в ФОИВ и региональные , а также правоохранительные органы о проблемных вопросах, требующих рассмотрения (не ответы на запросы)'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_6',
            field=models.PositiveIntegerField(default=0, verbose_name='159'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_7',
            field=models.PositiveIntegerField(default=0, verbose_name='165'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_8',
            field=models.PositiveIntegerField(default=0, verbose_name='160'),
        ),
        migrations.AddField(
            model_name='report',
            name='field_9',
            field=models.PositiveIntegerField(default=0, verbose_name='204'),
        ),
    ]
