# Generated by Django 5.0.6 on 2024-06-07 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmonths2024', '0003_report_field_1_report_field_10_report_field_11_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sixmonths2024.company', verbose_name='Компания/Филиал ПАО "Т Плюс"'),
        ),
        migrations.CreateModel(
            name='CreatorsSummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creators', models.ManyToManyField(related_name='summary_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
