# Generated by Django 5.0.6 on 2024-06-10 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmonths2024', '0005_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sixmonths2024.company', unique=True, verbose_name='Компания/Филиал ПАО "Т Плюс"'),
        ),
    ]
