# Generated by Django 5.0.6 on 2024-06-10 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmonths2024', '0006_alter_report_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixmonths2024.company', verbose_name='Компания/Филиал ПАО "Т Плюс"'),
        ),
    ]
